### ISSUE TITLE
Can't read in light mode

### ISSUE THREAD

**Issue by blissdev** [jamiebuilds/dark-mode-github-readme-logos#2]
Is this supposed to work in light mode as well? 

![Screen Shot 2020-12-08 at 5 34 21 PM](https://user-images.githubusercontent.com/3456/101554118-a3fd9e00-397b-11eb-98f8-b8e12c839a17.png)

**Comment by devivekw** [comment]
Same issue!

**Comment by g-ongenae** [comment]
I have the opposite issue. (Browser: Safari, Big Sur)
<img width="920" alt="Capture d’écran 2020-12-09 à 09 22 51" src="https://user-images.githubusercontent.com/9453090/101603747-50816380-3a00-11eb-8ad1-f36b0e073f96.png">
<img width="924" alt="Capture d’écran 2020-12-09 à 09 23 10" src="https://user-images.githubusercontent.com/9453090/101603751-51b29080-3a00-11eb-90cd-505330a92b35.png">

**Comment by devivekw** [comment]
> I have the opposite issue. (Browser: Safari, Big Sur)
> <img width="920" alt="Capture d’écran 2020-12-09 à 09 22 51" src="https://user-images.githubusercontent.com/9453090/101603747-50816380-3a00-11eb-8ad1-f36b0e073f96.png">
> <img width="924" alt="Capture d’écran 2020-12-09 à 09 23 10" src="https://user-images.githubusercontent.com/9453090/101603751-51b29080-3a00-11eb-90cd-505330a92b35.png">
> 
> 

That's interesting, I viewed it on Chromium, Windows

**Comment by simonhaenisch** [comment]
😂 

https://github.com/jamiebuilds/dark-mode-github-readme-logos/blob/9a4afedd22cd2e82e97067dbc4794c9f95264bf0/example.svg#L19

this is based on the system color scheme not the current site's color scheme 🤓
